# Generated by Django 5.1.4 on 2025-07-19 23:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventasapp', '0030_remove_business_stripe_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='stripe_secret_key',
            field=models.BinaryField(blank=True, null=True),
        ),
    ]
