# Generated by Django 5.1.4 on 2025-07-19 23:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventasapp', '0031_userprofile_stripe_secret_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='stripe_secret_key',
            field=models.CharField(blank=True, max_length=655, null=True),
        ),
    ]
