# Generated by Django 5.0.7 on 2025-07-23 18:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ventasapp', '0032_alter_userprofile_stripe_secret_key'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='business',
            name='stripe_account_id',
        ),
    ]
