# Generated by Django 5.0.7 on 2025-08-02 23:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventasapp', '0033_remove_business_stripe_account_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='metodo_pago',
            field=models.CharField(choices=[('tarjeta', 'Tarjeta de crédito/débito'), ('efectivo', 'Efectivo al recibir')], default='tarjeta', max_length=20, verbose_name='Método de pago'),
        ),
        migrations.AlterField(
            model_name='business',
            name='tipos_de_negocio',
            field=models.CharField(choices=[('restaurantes_formales', 'Restaurante Formal'), ('comida_rapida', 'Comida Rápida'), ('fondas_locales', 'Fonda o Comida Casera'), ('cafeterias', 'Cafetería'), ('panaderias_reposterias', 'Panadería o Pasteleria'), ('food_trucks', 'Food Truck'), ('licorerias', 'Licorería'), ('tiendas_helados_postres', 'Helados y Postres'), ('tiendas_saludables', 'Comida Saludable'), ('comida_vegana', 'Comida Vegana'), ('tiendas_locales_de_abarrotes', 'Tienda Local de Abarrotes'), ('medicamentos', 'Medicamentos y otros Productos de Farmacia'), ('tiendas_de_flores', 'Tiendas de flores'), ('tiendas_de_regalos', 'Tiendas de regalos')], max_length=200),
        ),
        migrations.AlterField(
            model_name='producto',
            name='tipo_subcategoria',
            field=models.CharField(choices=[('restaurantes_formales', 'Restaurante Formal'), ('comida_rapida', 'Comida Rápida'), ('fondas_locales', 'Fonda o Comida Casera'), ('cafeterias', 'Cafetería'), ('panaderias_reposterias', 'Panadería o Pasteleria'), ('food_trucks', 'Food Truck'), ('licorerias', 'Licorería'), ('tiendas_helados_postres', 'Helados y Postres'), ('tiendas_saludables', 'Comida Saludable'), ('comida_vegana', 'Comida Vegana'), ('tiendas_locales_de_abarrotes', 'Tienda Local de Abarrotes'), ('medicamentos', 'Medicamentos y otros Productos de Farmacia'), ('tiendas_de_flores', 'Tiendas de flores'), ('tiendas_de_regalos', 'Tiendas de regalos')], default='comida_rapida', max_length=100),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='giro_de_negocio',
            field=models.CharField(blank=True, choices=[('restaurantes_formales', 'Restaurante Formal'), ('comida_rapida', 'Comida Rápida'), ('fondas_locales', 'Fonda o Comida Casera'), ('cafeterias', 'Cafetería'), ('panaderias_reposterias', 'Panadería o Pasteleria'), ('food_trucks', 'Food Truck'), ('licorerias', 'Licorería'), ('tiendas_helados_postres', 'Helados y Postres'), ('tiendas_saludables', 'Comida Saludable'), ('comida_vegana', 'Comida Vegana'), ('tiendas_locales_de_abarrotes', 'Tienda Local de Abarrotes'), ('medicamentos', 'Medicamentos y otros Productos de Farmacia'), ('tiendas_de_flores', 'Tiendas de flores'), ('tiendas_de_regalos', 'Tiendas de regalos')], max_length=150, null=True),
        ),
    ]
