# Generated by Django 5.0.7 on 2025-08-04 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventasapp', '0034_pedido_metodo_pago_alter_business_tipos_de_negocio_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='business',
            name='acepta_efectivo',
            field=models.BooleanField(default=True, verbose_name='¿Acepta pagos en efectivo?'),
        ),
        migrations.AddField(
            model_name='business',
            name='acepta_tarjeta',
            field=models.BooleanField(default=True, verbose_name='¿Acepta pagos con tarjeta?'),
        ),
        migrations.AlterField(
            model_name='direcciondeenvio',
            name='notas',
            field=models.TextField(blank=True, default='', null=True),
        ),
    ]
