# Generated by Django 5.0.7 on 2025-08-04 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventasapp', '0035_business_acepta_efectivo_business_acepta_tarjeta_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='disponible_para_pedido',
            field=models.BooleanField(default=True, verbose_name='Disponible para pedidos'),
        ),
    ]
