# Generated by Django 5.0.7 on 2025-08-05 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventasapp', '0036_producto_disponible_para_pedido'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='is_approved',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='stripe_account_id',
        ),
        migrations.AlterField(
            model_name='producto',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
