# Generated by Django 5.0.7 on 2025-08-15 03:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventasapp', '0037_remove_userprofile_is_approved_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='business',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='business',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=11, null=True),
        ),
        migrations.AddField(
            model_name='direcciondeenvio',
            name='costo_envio',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
        ),
        migrations.AddField(
            model_name='direcciondeenvio',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='direcciondeenvio',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=11, null=True),
        ),
        migrations.AlterField(
            model_name='business',
            name='tipos_de_negocio',
            field=models.CharField(choices=[('restaurantes_formales', 'Restaurante Formal'), ('comida_rapida', 'Comida Rápida'), ('fondas_locales', 'Fonda o Comida Casera'), ('cafeterias', 'Cafetería'), ('panaderias_reposterias', 'Panadería o Pasteleria'), ('food_trucks', 'Food Truck'), ('licorerias', 'Licorería'), ('tiendas_helados_postres', 'Helados y Postres'), ('tiendas_saludables', 'Comida Saludable'), ('comida_vegana', 'Comida Vegana'), ('polleria', 'Polleria'), ('tiendas_locales_de_abarrotes', 'Tienda Local de Abarrotes'), ('medicamentos', 'Medicamentos y otros Productos de Farmacia'), ('tiendas_de_flores', 'Tiendas de flores'), ('tiendas_de_regalos', 'Tiendas de regalos')], max_length=200),
        ),
        migrations.AlterField(
            model_name='producto',
            name='tipo_subcategoria',
            field=models.CharField(blank=True, choices=[('restaurantes_formales', 'Restaurante Formal'), ('comida_rapida', 'Comida Rápida'), ('fondas_locales', 'Fonda o Comida Casera'), ('cafeterias', 'Cafetería'), ('panaderias_reposterias', 'Panadería o Pasteleria'), ('food_trucks', 'Food Truck'), ('licorerias', 'Licorería'), ('tiendas_helados_postres', 'Helados y Postres'), ('tiendas_saludables', 'Comida Saludable'), ('comida_vegana', 'Comida Vegana'), ('polleria', 'Polleria'), ('tiendas_locales_de_abarrotes', 'Tienda Local de Abarrotes'), ('medicamentos', 'Medicamentos y otros Productos de Farmacia'), ('tiendas_de_flores', 'Tiendas de flores'), ('tiendas_de_regalos', 'Tiendas de regalos')], default='comida_rapida', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='city',
            field=models.CharField(choices=[('puerto_vallarta', 'Puerto Vallarta'), ('cancun', 'Cancún'), ('cabo_sanlucas', 'Cabo San Lucas')], default='puerto_vallarta', max_length=50, verbose_name='Ciudad'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='giro_de_negocio',
            field=models.CharField(blank=True, choices=[('restaurantes_formales', 'Restaurante Formal'), ('comida_rapida', 'Comida Rápida'), ('fondas_locales', 'Fonda o Comida Casera'), ('cafeterias', 'Cafetería'), ('panaderias_reposterias', 'Panadería o Pasteleria'), ('food_trucks', 'Food Truck'), ('licorerias', 'Licorería'), ('tiendas_helados_postres', 'Helados y Postres'), ('tiendas_saludables', 'Comida Saludable'), ('comida_vegana', 'Comida Vegana'), ('polleria', 'Polleria'), ('tiendas_locales_de_abarrotes', 'Tienda Local de Abarrotes'), ('medicamentos', 'Medicamentos y otros Productos de Farmacia'), ('tiendas_de_flores', 'Tiendas de flores'), ('tiendas_de_regalos', 'Tiendas de regalos')], max_length=150, null=True),
        ),
    ]
